UPDATE mangos_string set content_loc8="Aльянс" WHERE entry=650;
UPDATE mangos_string set content_loc8="Oрда" WHERE entry=651;
UPDATE mangos_string set content_loc8="стойла" WHERE entry=652;
UPDATE mangos_string set content_loc8="кузницу" WHERE entry=653;
UPDATE mangos_string set content_loc8="ферму" WHERE entry=654;
UPDATE mangos_string set content_loc8="лесопилку" WHERE entry=655;
UPDATE mangos_string set content_loc8="золотой рудник" WHERE entry=656;
UPDATE mangos_string set content_loc8="%s захватывает %s" WHERE entry=657;
UPDATE mangos_string set content_loc8="$n защищает %s" WHERE entry=658;
UPDATE mangos_string set content_loc8="$n осаждает %s" WHERE entry=659;
UPDATE mangos_string set content_loc8="$n осаждает %s! Если не вернуть контроль, %s будет захвачена через 1 минуту!" WHERE entry=660;
UPDATE mangos_string set content_loc8="Орда собрала $1777W ресурсов и близка к победе!" WHERE entry=665;

UPDATE mangos_string set content_loc8="%s разрушена %s" WHERE entry=759;
UPDATE mangos_string set content_loc8="%s под атакой! Если не защитить, %s уничтожит её!" WHERE entry=760;
UPDATE mangos_string set content_loc8="%s захватывает %s" WHERE entry=761;
UPDATE mangos_string set content_loc8="%s захватывает %s" WHERE entry=762;
UPDATE mangos_string set content_loc8="%s захватывает %s" WHERE entry=763;
UPDATE mangos_string set content_loc8="%s под атакой! Если не защитить, %s захватит его!" WHERE entry=764;
UPDATE mangos_string set content_loc8="%s захватывает %s! Теперь его ресурсы будут использованны для подкрепления" WHERE entry=765;
UPDATE mangos_string set content_loc8="Железный рудник" WHERE entry=766;
UPDATE mangos_string set content_loc8="Ледяной рудник" WHERE entry=767;
UPDATE mangos_string set content_loc8="Лазарет Грозовой вершины" WHERE entry=768;
UPDATE mangos_string set content_loc8="Южная Башня Дун Балдара" WHERE entry=769;
UPDATE mangos_string set content_loc8="Северная Башня Дун Балдара" WHERE entry=770;
UPDATE mangos_string set content_loc8="Кладбище Грозовой вершины" WHERE entry=771;
UPDATE mangos_string set content_loc8="Башня Ледяного крыла" WHERE entry=772;
UPDATE mangos_string set content_loc8="Кладбище Каменного очага" WHERE entry=773;
UPDATE mangos_string set content_loc8="Башня Каменного очага" WHERE entry=774;
UPDATE mangos_string set content_loc8="Кладбище Снегопада" WHERE entry=775;
UPDATE mangos_string set content_loc8="Башня Стылой крови" WHERE entry=776;
UPDATE mangos_string set content_loc8="Кладбище Стылой крови" WHERE entry=777;
UPDATE mangos_string set content_loc8="Смотровая Башня" WHERE entry=778;
UPDATE mangos_string set content_loc8="Кладбище Северного волка" WHERE entry=779;
UPDATE mangos_string set content_loc8="Восточная Башня Северного волка" WHERE entry=780;
UPDATE mangos_string set content_loc8="Западная Башня Северного волка" WHERE entry=781;
UPDATE mangos_string set content_loc8="Приют Северного волка" WHERE entry=782;
UPDATE mangos_string set content_loc8="Генерал Северного волка погиб!" WHERE entry=789;
UPDATE mangos_string set content_loc8="Генерал Грозовой вершины погиб!" WHERE entry=790;
